image: node:latest

stages:
  - install
  - build-storybook
  - deploy-storybook

install:
  stage: install
  only:
    - main
  rules:
    - changes: apps/document/**/*
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/
  script:
    - yarn

build-storybook:
  stage: build-storybook
  only:
    - main
  rules:
    - changes: apps/document/**/*
  needs:
    - install
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
      - dist/storybook/document/
  script:
    - npx nx build-storybook document

pages:
  stage: deploy-storybook
  only:
    - main
  rules:
    - changes: apps/document/**/*
  needs:
    - build-storybook
  script:
    - rm -rf "public"
    - mkdir -p "public";
    - mv dist/storybook/document/* "public"
  artifacts:
    paths:
      - public
