image: node:latest

stages:
  - install
  - build-storybook
  - deploy-storybook

install:
  stage: install
  # rules:
  #   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  #     changes: 
  #       - apps/document/**/*
  before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install # install dependencies
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

build-storybook:
  stage: build-storybook
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
      - dist/storybook/document/
  script:
    - pnpm doc:build

pages:
  stage: deploy-storybook
  script:
    - rm -rf "public"
    - mkdir -p "public";
    - mv dist/storybook/document/* "public"
  artifacts:
    paths:
      - public
